// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beusgmqcwbmejxutgevn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJldXNnbXFjd2JtZWp4dXRnZXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODM1NDcsImV4cCI6MjA4NDc1OTU0N30.uf2XY8YAFD2o5F_FlBygP3F0wFGtisnBuGhk1APlKog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});