// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waehmrkxueixnckjgmfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZWhtcmt4dWVpeG5ja2pnbWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NzM3ODAsImV4cCI6MjA4NTM0OTc4MH0.bBxBdli458h_sDP99bRYf5PQ2GZNXtfgQ1G6hFNbDlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});